### ISSUE TITLE
Small elements not rendering

### ISSUE THREAD

**Issue by Tntnnbltn** [StrandedKitty/streets-gl#166]
The vector tile system loses details of small parts, which can include very small/thin building elements (on the scale of ~10 cm) being missing.

I modified planetiler and streets.gl locally to generate and run off of level 17 tiles instead of level 16, and the rendering of small elements noticeably improved. The following screenshots show the same building objects, using tile sets created with planetiler using zoom levels of 16 (left) and 17 (right), and then rendered in streets.gl using those respective tile sets. 

<img width="1470" alt="image" src="https://github.com/StrandedKitty/streets-gl/assets/108752678/ab01aee5-72b6-4257-84c5-193aec18aa8e">

<img width="1470" alt="image" src="https://github.com/StrandedKitty/streets-gl/assets/108752678/44b764c4-bbc7-4fb6-8a3f-88cb27cbec9a">

**Comment by StrandedKitty** [comment]
Related to https://github.com/StrandedKitty/streets-gl/issues/141

**Comment by StrandedKitty** [comment]
@Tntnnbltn Can you please share the location of these buildings on the screenshots?

**Comment by Tntnnbltn** [comment]
> @Tntnnbltn Can you please share the location of these buildings on the screenshots?

-32.148600, 115.934304
-32.126376, 115.925724

**Comment by StrandedKitty** [comment]
Fixed by increasing precision in Planetiler.

<img width="957" alt="Screenshot 2023-08-21 at 01 14 59" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/ead0b188-5462-480a-a5d5-f5c95606a670">

<img width="758" alt="Screenshot 2023-08-21 at 01 15 40" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/d7aeb180-96a9-4ea1-85c4-d85f5fb1a030">
