### ISSUE TITLE
Trees appear too bulky in some places on the map

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#49]
I wanted to take a look of how Streets GL rendered the [Gundam](https://www.openstreetmap.org/way/328166155) (F4 for comparison here):
![image](https://user-images.githubusercontent.com/94002623/236276883-cca2c01c-e135-4ec7-a477-33194cfad4b5.png)

But trees cover it:
![image](https://user-images.githubusercontent.com/94002623/236277012-942c31c9-7391-4cc7-ba41-c29d6208f5cf.png)

Based on aerial imagery F4 looks more similar to reality (Bing imagery):
![image](https://user-images.githubusercontent.com/94002623/236277156-458f5713-7411-41f3-ba77-0a1c3ab0f977.png)
maybe trees should be smaller by default? In my city also they look too bulky

p.s. have you considered enabling "Discussions" (e.g. https://github.com/streetcomplete/StreetComplete/discussions/) so we can discuss things there are not proper bugs?

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Is the _height_  - value on trees evaluated in streets.gl?

**Comment by StrandedKitty** [comment]
> Is the _height_ - value on trees evaluated in streets.gl?

Yes, it is supported for individual trees and tree rows.

**Comment by ivanbranco** [comment]
A 953m tree compared to normal trees
![image](https://user-images.githubusercontent.com/94002623/236330877-c4b8ed46-d13a-42f0-ad63-f409595ead8a.png)

**Comment by sekerob** [comment]
Who actually maps trees and rows with (estimated) heights and diameters? I don't, never ever, not encountered a natural / monumental tree that warrants the effort. Species could tell a little, orchard olives are 5-6m at best. Those street side certainly are pruned, all branches chopped to at least 5m from ground. Pines in the city usually have only the crown and in fact the Riserva Naturale Pineta here shows old to very old, only crown. Just added levels to apartment blocks on Via del Santuario, 7 at left, 5 at right, the pines lining the streets are reaching the top of the 4th floor.

![image](https://user-images.githubusercontent.com/23308504/236406703-79f49f1e-a919-467e-866f-0ceccf86cc50.png)

**Comment by westnordost** [comment]
> A 953m tree compared to normal trees

It's the mana tree from Secret of Mana! ;-)

---

Anyway, I compiled a small list of tags interesting for rendering in streets-gl from the information in the wiki in the hopes that this summary will be useful:

### Size

Your tree models are roughly 1:2, i.e. double as high as wide. So:

- use `height`, if not set `est_height` for height
- use `diameter_crown` for width (height ~= width * 2)

`circumference` of the trunk is set on *a lot* of trees, because it is easy to measure on foot (may even be a StreetComplete quest one day). `diameter` also exists. diameter = circumference / PI. A very rough estimate would be `diameter_crown` = `diameter` * 30. Hence:

- otherwise use `diameter` to estimate width
- otherwise use `circumference` to estimate width

### Type of tree

- for basic appearence: `leaf_type=needleleaved` or `leaf_type=broadleaved`
- use `leaf_cycle` to havve deciduous trees not have leaves in winter
- use `leaf_cycle` to fall back to a best guess if `leaf_type` is not specified

### Specific models for specific trees

(Over the top / blue sky:)

For certain (families of) trees with specific appearance that are often used as , I guess you need to look in any of `genus`, `species`, `species:wikidata`, `taxon` and even `species:<language>`, `genus:<language>` to find which tree is which with best coverage. Examples of trees with a special look and that are used often in cities from the top of my head:

- palm trees
- cherry trees (pink blossom in spring)
- apple trees (white blossom in spring)
- orange, lemon trees (etc.) (quite distinct due to the many fruits in the tree)

However, I think such detection would warrant a separate library project that heavily makes use of wikidata data best written in a language that can compile to various targets (JS, native, ...), e.g. in Kotlin or Rust. Such a library project could then maybe also make predictions on the width, height, relation to trunk diameter etc.

**Comment by benoit-dd** [comment]
I think that most tree height are integrated from opendata bases (for exemple in Paris: [this tree ](https://www.openstreetmap.org/node/7778255910) comes probably from [this database](https://opendata.paris.fr/explore/dataset/arbresremarquablesparis/map/?sort=arbres_hauteurenm&refine.com_arrondissement=17&basemap=jawg.dark&location=20,48.88767,2.31629))

Another funny example nearby:
![image](https://github.com/StrandedKitty/streets-gl/assets/52233014/feaa3bea-f6de-4972-af13-90d709753be5)
https://www.openstreetmap.org/node/5234550067#map=19/48.89506/2.31063
key| value
--|--
height | 60
leaf_type|broadleaved
min_height|57
natural|tree

It has probably been tagged so to look fine in f4map. but it's probably a pretty rare case

I think `location=roof+height=3` would be a better tagging and that it should give the same result.

About [sekerob](https://github.com/sekerob) comment on solar panel, I think `location=roof` should be used to put whatever (trees, pools, pitches,solarpanels?) on top of roofs (should it be a separate issue)?

**Comment by VladimirMorozov** [comment]
Units of measurement seem to be ignored 
diameter=15 cm

https://www.openstreetmap.org/node/6788395443
https://streets.gl/#59.43304,24.75283,29.75,132.25,1319.15
![изображение](https://github.com/StrandedKitty/streets-gl/assets/2279813/5ee6d61f-4ee4-4405-ad88-88b4893bcd81)

**Comment by StrandedKitty** [comment]
> Units of measurement seem to be ignored
> diameter=15 cm

Thank you for reporting this. I've added support for "cm" units, it's fine now.

**Comment by ivanbranco** [comment]
>![image](https://user-images.githubusercontent.com/94002623/236277012-942c31c9-7391-4cc7-ba41-c29d6208f5cf.png)

Now: 
![image](https://github.com/StrandedKitty/streets-gl/assets/94002623/01decc06-b310-482d-ba22-b14ea1568838)

Seems fixed, thanks!
