### ISSUE TITLE
roof:shape=round not shown

### ISSUE THREAD

**Issue by cebderby** [StrandedKitty/streets-gl#62]
Currently not showing roof:shape=round.  Spec has never been clear what to do if roof:height is not exactly half the relevant width but half an ellipse is probably ok for general case.  Is orientation = across/along (like gabled) to specify width vs length direction choice.  
Some example locations here:
https://streets.gl/#51.51294,-0.12221,40.25,222.00,123.70    (half round front)
https://streets.gl/#53.47602,-2.24705,39.00,246.25,357.24    (large rather shallow one)
https://streets.gl/#53.47695,-2.22934,29.75,307.50,346.27   (set of 4 side by side on building:part=roof)

**Comment by StrandedKitty** [comment]
Round roofs implemented in https://github.com/StrandedKitty/streets-gl/commit/cf53d5fae1c4ea9981c44edc4e85f1426b932a74.

<img width="1060" alt="Screenshot 2023-05-07 at 14 18 17" src="https://user-images.githubusercontent.com/48140945/236677021-490d661c-383e-479b-8279-0651974de733.png">

**Comment by sekerob** [comment]
Still not showing, maybe because I give them a roof:colour=lightgrey.

![image](https://user-images.githubusercontent.com/23308504/236686459-672c80c6-f982-41c7-a8b6-ccf7e7e1ea30.png)
Also noticed the oddest flickering only showing partial with the terrain elevation disabled.
![image](https://user-images.githubusercontent.com/23308504/236686831-cafe3215-cf02-4697-811a-f1b2d06b37a6.png)

The position as shown in standard Carto. A link to the building for the tagging.
https://www.openstreetmap.org/way/1167703980
![image](https://user-images.githubusercontent.com/23308504/236686645-ca5c2185-9981-42a2-adea-f653f6ed9c99.png)
