### ISSUE TITLE
New wood and forest will not render, loose trees/rows will.

### ISSUE THREAD

**Issue by sekerob** [StrandedKitty/streets-gl#91]
Noticed this since 3-4 days for new wood. Trees and tree-rows will show up. Also expanded wood will not render for the new section added. The old part continues to show though. To test just mapped a few tree groups river side, one with leave type specified, the other omitted, tagged as natural=wood.

![image](https://github.com/StrandedKitty/streets-gl/assets/23308504/224c927c-c011-418d-b4f4-07d84e4e249b)

I know the maps are updating as e.g. the school added just before shows up right bottom.

![image](https://github.com/StrandedKitty/streets-gl/assets/23308504/0edabc0b-abc5-4e0d-88ca-761fda5941fd)

**Comment by StrandedKitty** [comment]
Forest areas are fetched from Mapbox vector tiles API (see [StrandedKitty/streets-gl#%EF%B8%8F-data-sources)](https://github.com/StrandedKitty/streets-gl/blob/dev/README.md#%EF%B8%8F-data-sources). Mapbox probably doesn't update their tilesets very often.

Right now I'm starting to work on a server-side solution that would generate tiles for Streets GL directly from OSM data. Custom vector tileset will completely replace the data that's currently fetched from OSM using Overpass API and from Mapbox. This custom tileset won't update very ofter because it's not cheap, but rebuilding it every week or so should be fine.

**Comment by sekerob** [comment]
Thanks, not a bug, more of an enhancement WIP

PS: Observed the issue with water too yesterday. A reservoir, at least tagged like that in 2013, was in fact an olive orchard . Glistening surface in the morning setting has stayed put.
